baseURL = "https://vanleeuwen.studio/openff/"
languageCode = "en-us"
title = "OpenFF"
theme = "openff"

[params]
  header_title = "<b>open</b> force field"
  header_subtitle = "An open and collaborative approach to better force fields"
  "cc-by-4.0" = "https://creativecommons.org/licenses/by/4.0/"
  "cc-by-nc-nd-4.0" = "https://creativecommons.org/licenses/by/4.0/"
  "arxiv-1.0" = "https://arxiv.org/licenses/nonexclusive-distrib/1.0/license.html"

[menu]

  [[menu.main]]
    name = "About"
    url = "/about/mission/"
    identifier = "about"
    weight = 1

      [[menu.main]]
        name = "Mission"
        url = "/about/mission/"
        parent = "about"
        identifier = "mission"
        weight = 1

      [[menu.main]]
        name = "Team"
        url = "/about/team/"
        parent = "about"
        identifier = "team"
        weight = 3

      [[menu.main]]
        name = "Careers"
        url = "/about/careers/openff/initiative-postdoc/"
        parent = "about"
        identifier = "careers"
        weight = 10

      [[menu.main]]
        name = "Branding"
        url = "/about/branding/"
        parent = "about"
        identifier = "branding"
        weight = 11

      [[menu.main]]
        name = "Timeline"
        url = "/about/timeline/"
        parent = "about"
        identifier = "timeline"
        weight = 12

  [[menu.main]]
    name = "Science"
    url = "science/research"
    weight = 2
    identifier = "science"
    pre = "red"

      [[menu.main]]
        name = "Research"
        url = "/science/research/"
        parent = "science"
        identifier = "research"
        weight = 1

      [[menu.main]]
        name = "Publications"
        url = "/science/publications/"
        parent = "science"
        identifier = "publications"
        weight = 2

      [[menu.main]]
        name = "Collaborative projects"
        url = "/science/collaborative-projects/"
        parent = "science"
        identifier = "collaborative-projects"
        weight = 3

  [[menu.main]]
    name = "Software"
    url = "software"
    identifier = "software"
    weight = 4

  [[menu.main]]
    name = "Data"
    url = "data"
    identifier = "data"
    weight = 5

  [[menu.main]]
    name = "Force fields"
    url = "/force-fields/force-fields/"
    identifier = "force-fields"
    weight = 6

      [[menu.main]]
        name = "Force Fields"
        url = "/force-fields/force-fields/"
        parent = "force-fields"
        weight = 1

      [[menu.main]]
        name = "Versioning"
        url = "/force-fields/versioning/"
        parent = "force-fields"
        identifier = "versioning"
        weight = 2

  [[menu.main]]
    name = "Community"
    url = "community/news/news/"
    identifier = "community"
    weight = 7

      [[menu.main]]
        name = "News"
        url = "/community/news/news/"
        parent = "community"
        identifier = "news"
        weight = 1

      [[menu.main]]
        name = "Events"
        url = "/community/events/event-calendar/"
        parent = "community"
        identifier = "events"
        weight = 2

      [[menu.main]]
        name = "Collaborate"
        url = "/community/collaborate"
        parent = "community"
        identifier = "collaborate"
        weight = 3

      [[menu.main]]
        name = "FAQ"
        url = "/community/faq/"
        parent = "community"
        identifier = "faq"
        weight = 4

      [[menu.main]]
        name = "Forum"
        url = "/community/forum/"
        parent = "community"
        identifier = "forum"
        weight = 5
